/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PP_Factory_Method_Pessoa;

public class App {
   
    public static void main(String[] args) {
        Factory factory = new Factory();
        
        String nome = "Ana\n";
        String sexo = "Sexo F";
        
        factory.getPessoa(nome, sexo);
        
        nome = "Gustavo\n";
        sexo = "Sexo M";
        
        factory.getPessoa(nome, sexo);
        
    }

    public Object getGreeting() {
        return null;
    }
}
